# Generated by Django 5.1.3 on 2024-11-22 23:23

import django.db.models.deletion
import stor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('productType', models.IntegerField(choices=[(1, 'Quadra'), (2, 'Societ'), (3, 'Tenis'), (4, 'Volei'), (5, 'Voleiareia')], default=stor.models.ProductType['Quadra'])),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('userType', models.IntegerField(choices=[(1, 'Vendedor'), (2, 'Comprador')], default=stor.models.UserType['Comprador'])),
            ],
        ),
        migrations.CreateModel(
            name='ProductSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.IntegerField()),
                ('initialTime', models.TimeField()),
                ('finalTime', models.TimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.profile'),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentTime', models.TimeField()),
                ('isPaid', models.BooleanField(default=False)),
                ('productSchuedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.productschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('method', models.IntegerField(choices=[(1, 'Money'), (2, 'Pix'), (3, 'CreditCard'), (4, 'DebitCard')])),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.rent')),
            ],
        ),
    ]
