# Generated by Django 5.1 on 2024-08-30 23:32

import django.db.models.deletion
import stor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('productType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('userType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductSchuedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekDay', models.IntegerField()),
                ('InitialTime', models.TimeField()),
                ('FinalTime', models.TimeField()),
                ('Type', models.IntegerField(choices=[(1, 'Quadra'), (2, 'Societ'), (3, 'Tenis'), (4, 'Volei'), (5, 'Voleiareia')], default=stor.models.ProductType['Quadra'])),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.products')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentTime', models.TimeField()),
                ('ProductSchuedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.productschuedule')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('method', models.IntegerField(choices=[(1, 'Money'), (2, 'Pix'), (3, 'CreditCard'), (4, 'DebitCard')])),
                ('Rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stor.rent')),
            ],
        ),
    ]
